image: Visual Studio 2019

shallow_clone: true

platform:
  - Win32

configuration:
  - Release

matrix:
  fast_finish: false

only_commits:
  files:
    - /source/src/
    - /source/vc14/
    - .appveyor.yml
    - /source/cmake/

install:
  - cmd : vcpkg install boost-iostreams:x86-windows
  - cmd : vcpkg install boost-asio:x86-windows
  - cmd : vcpkg install boost-system:x86-windows
  - cmd : vcpkg install boost-filesystem:x86-windows
  - cmd : vcpkg install boost-variant:x86-windows
  - cmd : vcpkg install boost-lockfree:x86-windows
  - cmd : vcpkg install cryptopp:x86-windows
  - cmd : vcpkg install luajit:x86-windows
  - cmd : vcpkg install libmariadb:x86-windows
  - cmd : vcpkg install pugixml:x86-windows
  - cmd : vcpkg install mpir:x86-windows
  - cmd : vcpkg install spdlog:x86-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

after_build:
  - 7z a -tzip OTG.zip -r .\source\vc14\*.exe -ir!.\source\vc14\*.dll

cache:
  - c:\tools\vcpkg\installed\

artifacts:
  - path: \source\vc14\**\theforgottenserver*.exe
  - path: \source\vc14\**\*.dll
  - path: OTG.zip